-- insert into cliente(id_cliente, nome, renda)
    -- values(1, 'bruno rocha', 777.77);
-- insert into cliente(id_cliente, nome, renda)
    -- values(2, 'thiago dias', 111.11);
-- insert into cliente(id_cliente, nome, renda)
    -- values(3, 'thiago cury', 999.99);